baseURL: "https://pascalmichaillat.org/hugo-website/" 
title: Cesare Tinelli
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: papers/
          weight: 1
        - name: Talks
          url: talks/
          weight: 2
        - name: Projects
          url: projects/
          weight: 3
        - name: Honors
          url: honors/
          weight: 4
        - name: Credits
          url: credits/
          weight: 5
        - name: Advising
          url: advising/
          weight: 6
        - name: Courses
          url: courses/
          weight: 7
        - name: Service
          url: service/
          weight: 8 
        # - name: Blog
        #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
        #   weight: 6

params:
    author: Cesare Tinelli
    description: "This website hosts Prof. Cesare Tinelli's academic information."
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers","talks","projects","honors","credits","advising","courses","service","data"]
    ShowToc: false
    disableScrollToTop: false
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Professor Cesare Tinelli
          subtitle: "I am a Professor at the University of Iowa."
          imageUrl: "images/ct.jpg"
          imageWidth: 165
          imageHeight: 190
          buttons:
            - name: Publications
              url: papers/
            - name: "Selected Talks"
              url: talks/
            - name: "Projects & Grants"
              url: projects/
            # - name: Books
            #   url: books/
            - name: Acknowledgments
              url: credit/
            - name: "Honors & Awards"
              url: honors/
            - name: "Advising"
              url: advising/
            - name: Courses
              url: courses/
            - name: Service
              url: service/
            # - name: Tags
            #   url: tags/
            # - name: Archive
            #   url: archive/
            # - name: Blog
            #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: docs/cv.pdf
        # - name: Email
        #   url: mailto:user@gmail.com
        # - name: Zoom
        #   url: https://www.zoom.us/my/user
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=wbZc9nUAAAAJ&hl=en
        - name: ORCID ID
          url: https://orcid.org/0000-0002-6726-775X
        # - name: GitHub
        #   url: https://github.com/user
        # - name: YouTube
        #   url: https://www.youtube.com/@user
        # - name: Substack
        #   url: https://user.substack.com
        # - name: Twitter
        #   url: https://x.com/user
        # - name: Bluesky
        #   url: https://bsky.app/profile/user.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Cesare Tinelli"
      icon: images/home.png
      iconHeight: 20

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2